# Markdown Linting Configuration for Super Linter
# This configuration works with markdownlint-cli2 used by Super Linter

# Extend the default configuration
extends: markdownlint/style/prettier

# Custom rules for technical documentation
rules:
  # Line length - allow longer lines for URLs and code blocks
  MD013:
    line_length: 180
    heading_line_length: 120
    code_block_line_length: 180
    tables: false
    headings: false
    headers: false

  # Heading styles - enforce ATX headers (# style)
  MD003:
    style: atx

  # Unordered list style - consistent bullet points
  MD004:
    style: dash

  # List indentation - consistent 2-space indentation
  MD007:
    indent: 2
    start_indented: false

  # Code fence style - enforce fenced code blocks
  MD046:
    style: fenced

  # Inline HTML - allow HTML for complex formatting
  MD033: false

  # Bare URLs - allow bare URLs in documentation
  MD034: false

  # First line heading - don't require H1 as first line
  MD041: false

  # Emphasis markers - consistent underscore for emphasis
  MD049:
    style: underscore

  # Strong markers - consistent asterisk for strong
  MD050:
    style: asterisk

# Ignore files and patterns
ignores:
  # Ignore auto-generated files
  - "CHANGELOG.md"
  - "node_modules/"
  - ".git/"
  - "*.log"
  # Ignore files with template syntax that might confuse the linter
  - "**/molecule/**"
  - "**/.github/**"
