---
# Prettier configuration for JavaScript, TypeScript, JSON, CSS, HTML, and Markdown
# Compatible with Prettier 2.x and 3.x

# Print width - line length that prettier will try to wrap on
printWidth: 120

# Tab width - number of spaces per indentation level
tabWidth: 2

# Use tabs instead of spaces
useTabs: false

# Add semicolons at the end of statements
semi: true

# Use single quotes instead of double quotes
singleQuote: true

# Quote props in objects only when needed
quoteProps: "as-needed"

# Use trailing commas where valid in ES5 (objects, arrays, etc.)
trailingComma: "es5"

# Add spaces inside bracket pairs
bracketSpacing: true

# Put the > of a multi-line JSX element at the end of the last line
bracketSameLine: false

# Include parentheses around a sole arrow function parameter
arrowParens: "avoid"

# Range formatting - format entire file
rangeStart: 0
rangeEnd: 999999

# Parser - let prettier auto-detect
# parser: ""

# File path - use for debugging
# filepath: ""

# Require pragma comment to format
requirePragma: false

# Insert pragma comment after formatting
insertPragma: false

# Wrap prose (markdown) if it exceeds print width
proseWrap: "preserve"

# HTML whitespace sensitivity
htmlWhitespaceSensitivity: "css"

# Vue files script and style tags indentation
vueIndentScriptAndStyle: false

# Line ending style
endOfLine: "lf"

# Embedded language formatting
embeddedLanguageFormatting: "auto"

# Single attribute per line in HTML, Vue, JSX
singleAttributePerLine: false

# Override settings for specific file types
overrides:
  # YAML files
  - files: "*.{yml,yaml}"
    options:
      tabWidth: 2
      printWidth: 180
      singleQuote: false

  # JSON files
  - files: "*.json"
    options:
      tabWidth: 2
      printWidth: 120
      trailingComma: "none"

  # Markdown files
  - files: "*.{md,markdown}"
    options:
      tabWidth: 2
      printWidth: 180
      proseWrap: "preserve"
      embeddedLanguageFormatting: "auto"

  # HTML files
  - files: "*.{html,htm}"
    options:
      tabWidth: 2
      printWidth: 120
      htmlWhitespaceSensitivity: "strict"

  # CSS/SCSS files
  - files: "*.{css,scss,sass}"
    options:
      tabWidth: 2
      printWidth: 120
      singleQuote: true

  # JavaScript files
  - files: "*.{js,jsx}"
    options:
      tabWidth: 2
      printWidth: 120
      semi: true
      singleQuote: true
      trailingComma: "es5"

  # TypeScript files
  - files: "*.{ts,tsx}"
    options:
      tabWidth: 2
      printWidth: 120
      semi: true
      singleQuote: true
      trailingComma: "es5"

  # Configuration files
  - files: "*.{json,jsonc,json5}"
    options:
      tabWidth: 2
      printWidth: 120
      trailingComma: "none"
      quoteProps: "preserve"

  # Package.json files
  - files: "package*.json"
    options:
      tabWidth: 2
      printWidth: 120
      trailingComma: "none"
