---
# Legacy Playbook - Maintained for Backward Compatibility
# 
# 🔄 MODERNIZED STRUCTURE AVAILABLE!
# This playbook has been modularized for better maintainability.
# 
# New structure:
# - playbooks/main.yml              # Main orchestrator
# - playbooks/01-validate-environment.yml
# - playbooks/02-convert-templates.yml  
# - playbooks/03-convert-html.yml
# - playbooks/04-publish-confluence.yml
# - playbooks/cleanup.yml
#
# Usage:
#   ansible-playbook playbooks/main.yml        # Run all steps
#   ansible-playbook playbooks/cleanup.yml     # Clean up files
#
# This legacy playbook will run the modular version for compatibility

- name: "🔄 Confluence Documentation Automation (Legacy Wrapper)"
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: "ℹ️  Legacy playbook detected"
      ansible.builtin.debug:
        msg: |
          ================================================
          📢 NOTICE: Using Legacy Playbook
          ================================================
          
          This playbook has been modularized for better maintainability!
          
          🆕 New modular structure available:
          - playbooks/main.yml (main orchestrator)
          - playbooks/01-validate-environment.yml
          - playbooks/02-convert-templates.yml
          - playbooks/03-convert-html.yml
          - playbooks/04-publish-confluence.yml
          - playbooks/cleanup.yml
          
          💡 Recommended usage:
          ansible-playbook playbooks/main.yml
          
          ⏳ Continuing with legacy execution...
          ================================================

    - name: "🚀 Executing modular playbook"
      ansible.builtin.include: playbooks/main.yml
