---
# Verification for syntax check scenario

- name: Verify syntax and structure
  hosts: localhost
  gather_facts: false
  tasks:
    - name: "Confirm yamllint configuration exists"
      ansible.builtin.stat:
        path: .yamllint
      register: yamllint_config

    - name: "Verify yamllint config is present"
      ansible.builtin.assert:
        that:
          - yamllint_config.stat.exists
        fail_msg: "yamllint configuration file missing"
        success_msg: "yamllint configuration found"

    - name: "Check ansible-lint compatibility"
      ansible.builtin.command: ansible-lint --version
      register: ansible_lint_version
      changed_when: false
      failed_when: false

    - name: "Verify linting tools are available"
      ansible.builtin.debug:
        msg: "Linting tools status - ansible-lint: {{ 'available' if ansible_lint_version.rc == 0 else 'missing' }}"

    - name: "Validate Makefile targets"
      ansible.builtin.shell: grep -E "^[a-zA-Z-]+:" Makefile | head -5
      register: makefile_targets
      changed_when: false

    - name: "Display available make targets"
      ansible.builtin.debug:
        msg: "Available targets: {{ makefile_targets.stdout_lines }}"

    - name: "Check documentation completeness"
      ansible.builtin.stat:
        path: "{{ item }}"
      register: docs
      loop:
        - YAML_LINTING_STANDARDS.md
        - MOLECULE_TESTING_GUIDE.md
        - README.md

    - name: "Verify documentation exists"
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "Documentation file {{ item.item }} is missing"
        success_msg: "Documentation file {{ item.item }} exists"
      loop: "{{ docs.results }}"
      when: item.item != "README.md"  # README might not exist yet
