---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: playbook-test
    image: quay.io/ansible/molecule-ubuntu:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer,yaml
      stdout_callback: yaml
      verbosity: 1
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      playbook-test:
        ansible_user: ansible
  lint: |
    set -e
    yamllint -c .yamllint .
    ansible-lint
verifier:
  name: ansible
