---
# Molecule verification tests

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: "Check if pandoc is installed"
      ansible.builtin.command: pandoc --version
      register: pandoc_version
      changed_when: false

    - name: "Verify pandoc installation"
      ansible.builtin.assert:
        that:
          - pandoc_version.rc == 0
        fail_msg: "Pandoc is not properly installed"
        success_msg: "Pandoc is installed and working"

    - name: "Check generated HTML files"
      ansible.builtin.stat:
        path: "/tmp/{{ item }}.html"
      register: generated_files
      loop:
        - main.md
        - test_page1.md
        - test_page2.md

    - name: "Verify all HTML files were generated"
      ansible.builtin.assert:
        that:
          - item.stat.exists
          - item.stat.size > 0
        fail_msg: "Generated file {{ item.item }}.html is missing or empty"
        success_msg: "Generated file {{ item.item }}.html exists and has content"
      loop: "{{ generated_files.results }}"

    - name: "Verify HTML content structure"
      ansible.builtin.shell: grep -q "Test Project" /tmp/main.md.html
      register: content_check
      changed_when: false
      failed_when: content_check.rc != 0

    - name: "Test template variable substitution"
      ansible.builtin.lineinfile:
        path: /tmp/main.md.html
        line: "Test Project"
        state: present
      check_mode: true
      register: template_test

    - name: "Verify template processing worked"
      ansible.builtin.assert:
        that:
          - not template_test.changed
        fail_msg: "Template variables were not properly substituted"
        success_msg: "Template processing successful"

    - name: "Check for security issues in templates"
      ansible.builtin.shell: |
        # Check for potential security issues in generated content
        ! grep -i "password\|secret\|token\|key" /tmp/*.html || echo "Security check passed"
      register: security_check
      changed_when: false
      failed_when: false

    - name: "Display security check results"
      ansible.builtin.debug:
        msg: "Security scan completed: {{ security_check.stdout }}"
