---
- name: "Test URL Encoding"
  hosts: localhost
  gather_facts: false
  vars:
    confluence_url: "https://alexgambino22.atlassian.net/wiki"
    confluence_space: "Ansible"
    project_name: "Your Project Name"

  tasks:
    - name: "Test URL encoding - Main page query"
      ansible.builtin.debug:
        msg: |
          Main page query URL:
          {{ confluence_url }}/rest/api/content?title={{ (project_name + ' Documentation') | urlencode }}&spaceKey={{ confluence_space }}&expand=version

    - name: "Test URL encoding - Child page query"
      ansible.builtin.debug:
        msg: |
          Child page query URL:
          {{ confluence_url }}/rest/api/content?title={{ item.title | urlencode }}&spaceKey={{ confluence_space }}&expand=version
      loop:
        - title: "Platform Governance"
        - title: "Platform Runbook"
        - title: "Operator Runbook"
        - title: "Training & Enablement"

    - name: "Test that URLs contain no spaces"
      ansible.builtin.assert:
        that:
          - "' ' not in url"
        fail_msg: "URL contains spaces: {{ url }}"
        success_msg: "URL is properly encoded: {{ url }}"
      vars:
        url: "{{ confluence_url }}/rest/api/content?title={{ (project_name + ' Documentation') | urlencode }}&spaceKey={{ confluence_space }}&expand=version"
