# Bitbucket Pipelines Configuration
# Copy this to bitbucket-pipelines.yml for Bitbucket CI/CD

image: python:3.11

definitions:
  caches:
    pip: ~/.cache/pip
  
  steps:
    - step: &install-deps
        name: Install Dependencies
        script:
          - apt-get update && apt-get install -y make yamllint pandoc
          - pip install --upgrade pip
          - pip install ansible-lint ansible
        caches:
          - pip
    
    - step: &sanity-check
        name: Sanity Check
        script:
          - make sanity-check
        caches:
          - pip
    
    - step: &security-scan
        name: Security Scan
        script:
          - make security-check
        after-script:
          - echo "Security scan completed"
        artifacts:
          - "**/*security*"
          - "**/*report*"
    
    - step: &lint
        name: Lint and Validate
        script:
          - make lint
          - make validate-templates
        caches:
          - pip
    
    - step: &full-validation
        name: Full Validation
        script:
          - make validate
          - make test-render
        caches:
          - pip
        artifacts:
          - "**/*.log"
          - "**/test-results.*"

pipelines:
  default:
    - step: *install-deps
    - step: *sanity-check
    - parallel:
        - step: *security-scan
        - step: *lint
  
  branches:
    main:
      - step: *install-deps
      - step: *sanity-check
      - parallel:
          - step: *security-scan
          - step: *lint
      - step: *full-validation
      - step:
          name: Molecule Testing
          script:
            - pip install molecule[docker]
            - molecule test || echo "Molecule tests failed - continuing"
          services:
            - docker
          caches:
            - pip
          artifacts:
            - "**/molecule-results.*"
    
    develop:
      - step: *install-deps
      - step: *sanity-check
      - parallel:
          - step: *security-scan
          - step: *lint
      - step: *full-validation
  
  pull-requests:
    '**':
      - step: *install-deps
      - step: *sanity-check
      - step: *lint

  tags:
    release-*:
      - step: *install-deps
      - step: *full-validation
      - step:
          name: Release Validation
          script:
            - echo "Release validation complete"
            - make validate

options:
  max-time: 30
