---
# GitLab CI/CD Configuration
# Copy this to .gitlab-ci.yml to enable GitLab CI/CD

stages:
  - validate
  - test
  - security
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

# Lint and validate YAML/Ansible
lint:
  stage: validate
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make yamllint
    - pip install ansible-lint
  script:
    - make lint
  only:
    - merge_requests
    - main
    - develop
  except:
    - tags

# Security scanning
security:
  stage: security
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make
  script:
    - make security-check
  allow_failure: false
  only:
    - merge_requests
    - main
    - develop
  artifacts:
    reports:
      # Add security scan results if available
    when: always
    expire_in: 1 week

# Syntax and template validation
validate:
  stage: test
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make yamllint pandoc
    - pip install ansible-lint ansible
  script:
    - make validate
  only:
    - merge_requests
    - main
    - develop
  artifacts:
    reports:
      junit: test-results.xml
    when: always
    expire_in: 1 week

# Quick sanity checks for feature branches
sanity:
  stage: validate
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make yamllint
    - pip install ansible-lint ansible
  script:
    - make sanity-check
  only:
    - branches
  except:
    - main
    - develop
    - tags

# Molecule testing (when Docker is available)
molecule:
  stage: test
  image: quay.io/ansible/molecule:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - pip install molecule[docker]
  script:
    - molecule test
  only:
    - main
    - develop
  allow_failure: true  # Allow failure until full setup

# Template deployment validation
deploy-check:
  stage: deploy
  image: python:3.11-slim
  before_script:
    - apt-get update && apt-get install -y make yamllint pandoc
    - pip install ansible-lint ansible
  script:
    - make test-render
  only:
    - main
  when: manual
