---
# Markdown to HTML Conversion Playbook
# Converts markdown files to HTML using pandoc via make targets

- name: "Markdown to HTML Conversion"
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../vars/vars.yml

  tasks:
    - name: "Convert markdown to HTML using make"
      block:
        - name: "Convert markdown files to HTML"
          ansible.builtin.command: make -C .. convert-markdown
          register: markdown_conversion
          changed_when: true

        - name: "Debug - Show markdown conversion result"
          ansible.builtin.debug:
            msg: |
              Markdown conversion result:
              Return code: {{ markdown_conversion.rc }}
              Output: {{ markdown_conversion.stdout }}
              Errors: {{ markdown_conversion.stderr | default('None') }}

        - name: "Verify HTML files using make"
          ansible.builtin.command: make -C .. verify-html
          register: html_verification
          changed_when: false

        - name: "Debug - Show HTML verification result"
          ansible.builtin.debug:
            msg: |
              HTML verification result:
              {{ html_verification.stdout }}

      rescue:
        - name: "Handle conversion errors"
          ansible.builtin.debug:
            msg: "Markdown to HTML conversion failed. Please check the debug output above."

        - name: "Show environment info for troubleshooting"
          ansible.builtin.debug:
            msg: |
              Troubleshooting info:
              - Current user: {{ ansible_env.USER | default('unknown') }}
              - Working directory: {{ ansible_env.PWD | default('unknown') }}
              - ~/tmp permissions: {{ ansible_env.USER | default('current user') }} should have write access

        - name: "Fail with helpful message"
          ansible.builtin.fail:
            msg: |
              Markdown to HTML conversion failed. Common issues:
              1. Pandoc not installed or not in PATH
              2. Source markdown files missing or corrupted
              3. Insufficient permissions to write to ~/tmp
              4. Pandoc version compatibility issues

              Manual test: pandoc ~/tmp/main.md -f markdown -t html -o ~/tmp/test.html

    - name: "Fallback conversion if make failed"
      block:
        - name: "Fallback: Try make convert-all"
          ansible.builtin.command: make -C .. convert-all
          register: fallback_conversion
          when: markdown_conversion.rc != 0
          changed_when: true
          failed_when: false

        - name: "Final verification of HTML files"
          ansible.builtin.command: make -C .. verify-html
          register: final_verification
          changed_when: false

        - name: "Report final conversion status"
          ansible.builtin.debug:
            msg: |
              Final verification result:
              {{ final_verification.stdout }}

      rescue:
        - name: "Handle fallback conversion errors"
          ansible.builtin.debug:
            msg: |
              Fallback conversion also failed.
              Please check the system manually:
              - Ensure pandoc is installed: which pandoc
              - Test manually: make convert-all
              - Check ~/tmp directory permissions

        - name: "Show final troubleshooting info"
          ansible.builtin.debug:
            msg: |
              Troubleshooting info:
              - Current user: {{ ansible_env.USER | default('unknown') }}
              - Working directory: {{ ansible_env.PWD | default('unknown') }}
              - ~/tmp permissions: {{ ansible_env.USER | default('current user') }} should have write access

        - name: "Fail with helpful message"
          ansible.builtin.fail:
            msg: |
              Fallback conversion to HTML failed. Common issues:
              1. Pandoc not installed or not in PATH
              2. Source markdown files missing or corrupted
              3. Insufficient permissions to write to ~/tmp
              4. Pandoc version compatibility issues

              Manual test: pandoc ~/tmp/main.md -f markdown -t html -o ~/tmp/test.html
