---
# Enhanced Confluence Publishing Playbook  
# Handles page creation and updates for both static and auto-document content

- name: Enhanced Documentation Publishing
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../vars/vars.yml
    
  tasks:
    - name: "📊 Discovery and Publishing Overview"
      ansible.builtin.debug:
        msg: |
          ================================================
          📊 Enhanced Confluence Publishing
          ================================================
          Confluence URL: {{ confluence_url }}
          Space: {{ confluence_space }}
          Project: {{ project_name }}
          ================================================
          
    - name: Discover all documentation sections
      ansible.builtin.command:
        cmd: python3 scripts/discover_docs_enhanced.py
        chdir: ".."
      register: discovery_result
      
    - name: Parse discovery results
      ansible.builtin.set_fact:
        doc_sections: "{{ discovery_result.stdout | from_json }}"
        
    - name: "📋 Show discovered sections"
      ansible.builtin.debug:
        msg: |
          Discovered {{ doc_sections | length }} documentation section(s):
          {% for section_name, section_info in doc_sections.items() %}
          - {{ section_name }}: {{ section_info.children | length }} children, {{ section_info.nested_sections | length }} nested
          {% endfor %}
        
    - name: Publish main page (Automation Hub) to Confluence
      include_tasks: tasks/publish_confluence_page.yml
      vars:
        page_title: "Automation Hub"
        page_content: "{{ lookup('file', '/home/gambia/tmp/automation_hub.md') }}"
        parent_page: ""
        is_auto_document: false
      when: "'automation_hub' in doc_sections"
        label: "{{ section_item.key }}"
      vars:
        section_info: "{{ section_item.value }}"
      when: section_info.main_template is defined        
    - name: Publish child pages to Confluence
      include_tasks: tasks/publish_confluence_page.yml
      vars:
        page_title: "{{ child.name | title }}"
        page_content: "{{ lookup('file', '/home/gambia/tmp/' + child.name + '.md') }}"
        parent_page: "Automation Hub"
        is_auto_document: false
      loop: "{{ doc_sections.automation_hub.children | default([]) }}"
      loop_control:
        loop_var: child
      when: "'automation_hub' in doc_sections"
