---
name: Molecule CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run Molecule tests using molecule-action
        uses: gofrolist/molecule-action@v2
        with:
          args: test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          # The following secrets must be defined in GitHub repository settings under Settings → Secrets and variables → Actions
          # CONFLUENCE_URL
          # CONFLUENCE_SPACE
          # CONFLUENCE_AUTH
