---
name: Molecule CI

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Run Molecule tests using molecule-action
        uses: gofrolist/molecule-action@v1
        with:
          molecule_command: test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          CONFLUENCE_URL: "http://localhost"
          CONFLUENCE_SPACE: "TEST"
          CONFLUENCE_AUTH: "dummy"
