# .github/workflows/test-publisher.yml
name: Test Reusable Publisher

# Trigger on pull requests made to this repository
on:
  push:
    branches:
      - main
      - develop
      # Feature branches - multiple prefixes supported
      - 'feature/**'     # feature/user-management, feature/auth/login, etc.
      - 'feature/*'      # feature/login, feature/user-auth, etc.
      - 'ft/**'          # ft/user-management, ft/auth/login, etc.
      - 'ft/*'           # ft/login, ft/user-auth, etc.
      # Release branches
      - 'release/**'     # release/v1.2.0, release/hotfix/v1.1.1, etc.
      - 'release/*'      # release/v1.2.0, release/sprint-1, etc.
      - 'rel/**'         # rel/v1.2.0 (alternative prefix)
      - 'rel/*'          # rel/v1.2.0 (alternative prefix)
      # Hotfix branches
      - 'hotfix/**'      # hotfix/critical-bug, hotfix/security/auth-fix, etc.
      - 'hotfix/*'       # hotfix/critical-bug, hotfix/auth-fix, etc.
      - 'hf/**'          # hf/critical-bug (alternative prefix)
      - 'hf/*'           # hf/critical-bug (alternative prefix)

jobs:
  test_the_reusable_workflow:
    # This job calls the *other* workflow file in this same repo
    uses: KhalilGibrotha/redesigned-guacamole/.github/workflows/ci.yml@main

    # It passes the secrets needed for the test run
    secrets:
      CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
      CONFLUENCE_USER: ${{ secrets.CONFLUENCE_USER }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}