name: Test Secrets Handling

on:
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Test mode (with-secrets or without-secrets)'
        required: true
        default: 'without-secrets'
        type: choice
        options:
          - 'with-secrets'
          - 'without-secrets'

jobs:
  test-confluence-secrets:
    name: 🧪 Test Confluence Secrets Handling
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test Secret Validation Logic
        run: |
          echo "🧪 Testing Confluence secrets validation logic..."

          # Simulate the validation logic from our workflow
          if [ "${{ inputs.test_mode }}" = "with-secrets" ]; then
            # Simulate having secrets
            CONFLUENCE_URL="https://test.atlassian.net"
            CONFLUENCE_USER="test@example.com"
            CONFLUENCE_API_TOKEN="test-token"
          else
            # Simulate missing secrets (empty values)
            CONFLUENCE_URL=""
            CONFLUENCE_USER=""
            CONFLUENCE_API_TOKEN=""
          fi

          echo "📊 Secret Availability Check:"
          echo "  - CONFLUENCE_URL defined: $([ -n "$CONFLUENCE_URL" ] && echo 'true' || echo 'false')"
          echo "  - CONFLUENCE_USER defined: $([ -n "$CONFLUENCE_USER" ] && echo 'true' || echo 'false')"
          echo "  - CONFLUENCE_API_TOKEN defined: $([ -n "$CONFLUENCE_API_TOKEN" ] && echo 'true' || echo 'false')"

          # Check if all secrets are available
          if [ -n "$CONFLUENCE_URL" ] && [ -n "$CONFLUENCE_USER" ] && [ -n "$CONFLUENCE_API_TOKEN" ]; then
            SECRETS_AVAILABLE=true
            echo "✅ All Confluence secrets are available"
          else
            SECRETS_AVAILABLE=false
            echo "❌ Some Confluence secrets are missing"
          fi

          # Determine effective dry-run mode
          DRY_RUN_INPUT="false"  # Simulate dry_run: false from workflow input
          if [ "$SECRETS_AVAILABLE" = "false" ]; then
            EFFECTIVE_DRY_RUN=true
            echo "🔄 Auto-enabling dry-run mode due to missing secrets"
          else
            EFFECTIVE_DRY_RUN="$DRY_RUN_INPUT"
            echo "⚙️ Using input dry-run setting: $DRY_RUN_INPUT"
          fi

          echo "📊 Final Configuration:"
          echo "  - Input dry-run: $DRY_RUN_INPUT"
          echo "  - Secrets available: $SECRETS_AVAILABLE"
          echo "  - Effective dry-run: $EFFECTIVE_DRY_RUN"

          if [ "$EFFECTIVE_DRY_RUN" = "true" ]; then
            echo "🔸 Would run in DRY-RUN mode (no actual publishing)"
            if [ "$SECRETS_AVAILABLE" = "false" ]; then
              echo "💡 To enable live publishing, configure Confluence secrets in repository settings"
            fi
          else
            echo "🚀 Would run in LIVE mode (actual publishing)"
          fi

          echo "✅ Secret validation test completed successfully"

  test-workflow-call:
    name: 🔗 Test via Workflow Call
    uses: ./.github/workflows/ci-optimized.yml
    with:
      auto_fix: true
      dry_run: false  # This should be overridden to true due to missing secrets
    # Note: No secrets passed - this should trigger auto-dry-run mode
